name: infra pipeline
on:
    pull_request:
        branches: [ "main" ]
    push:
        branches: ["main"]
permissions:
  id-token: write
  contents: read

jobs:
    build:
        runs-on: ubuntu-latest
        defaults:
            run:
                working-directory: ./terraform
        steps:
            - name: Checkout code
              uses: actions/checkout@v6.0.2

            - name: AWS creds
              uses: aws-actions/configure-aws-credentials@v6.1.0
              with:
                role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
                aws-region: eu-west-2

            - name: terraform setup
              uses: hashicorp/setup-terraform@v4.0.0

            - name: terraform init
              run: terraform init

            - name: terraform fmt
              run: terraform fmt -check

            - name: terraform validate
              run: terraform validate

            - name: Checkov GitHub Action
              uses: bridgecrewio/checkov-action@master
              with:
                 directory: ./terraform
                 skip_check: CKV_TF_1,CKV_K8S_43

            - name: Grype Scan
              uses: anchore/scan-action@v7.4.0
              with:
                path: "./terraform"
                fail-build: false

            - name: terraform import cluster creator
              run: terraform import 'module.eks.aws_eks_access_entry.this["cluster_creator"]' eks-labs:${{ secrets.AWS_ROLE_ARN }}
              continue-on-error: true

            - name: terraform plan
              run: terraform plan

            - name: terraform apply
              if: github.event_name == 'push'
              run: terraform apply -auto-approve
