name: docker-pipeline
on:
    push:
        branches: ["main"]
        paths:
          - "app/**"
permissions:
  id-token: write
  contents: write

jobs:
    build:
        runs-on: ubuntu-latest
        env:
            ECR_REGISTRY: 275333454194.dkr.ecr.eu-west-2.amazonaws.com
        defaults:
            run:
                working-directory: ./app
        steps:
            - name: Checkout code
              uses: actions/checkout@v6.0.2

            - name: AWS creds
              uses: aws-actions/configure-aws-credentials@v6.1.0
              with:
                role-to-assume: ${{ secrets.AWS_ROLE_ARN }}
                aws-region: eu-west-2

            - name: Login to ECR
              uses: aws-actions/amazon-ecr-login@v2

            - name: Grype Scan
              uses: anchore/scan-action@v7.4.0
              with:
                path: "."
                fail-build: false

            - name: Build image
              run: |
                docker build -t ${{ env.ECR_REGISTRY }}/platform-status:${{ github.sha }} .
                docker push ${{ env.ECR_REGISTRY }}/platform-status:${{ github.sha }}

            - name: Update image tag
              working-directory: ./apps
              run: |
                sed -i "s|platform-status:.*|platform-status:${{ github.sha }}|" app-hub.yml
                git config user.name "github-actions"
                git config user.email "github-actions@github.com"
                git add app-hub.yml
                git commit -m "chore: update image tag to ${{ github.sha }}"
                git push
